### ISSUE TITLE
seedにownerのemailを保存する方法がわかりません

### ISSUE THREAD

**Issue by haruka0000** [NIT-Anan-Procon/rails_pokereg#6]

**Comment by haruka0000** [comment]
![screenshot from 2015-03-06 00 25 42](https://cloud.githubusercontent.com/assets/8327769/6507781/e48f9e24-c397-11e4-878a-d2ae6542fafb.png)

rake db:seedのエラー内容
![screenshot from 2015-03-06 00 27 00](https://cloud.githubusercontent.com/assets/8327769/6507784/e58e0e6e-c397-11e4-88dd-bd50d78024de.png)
![screenshot from 2015-03-06 00 27 07](https://cloud.githubusercontent.com/assets/8327769/6507787/eac4b41e-c397-11e4-9cc5-06a65f1a3124.png)

この状態でrake db:seed しました

**Comment by haruka0000** [comment]
多分まだbelongｓ_toとか他のテーブルと結びつけるというところが理解できてないところがあります

**Comment by kjmtks** [comment]
belongs_to はそのモデルが他モデルへの参照を持つことを表明するものです。
このケースだと Thingモデルは Userモデルへの参照をownerという名前で持つことを表明しています。
それぞれのモデルに対応するテーブル、thigs, usersの依存関係は次のようになっています。
  things  -----依存-----> users
これをthingsはusersに属していると考え、belongs_toというメソッド名になっているんだと思います。

ちなみに、参照の名前がownerではなくuserのとき、自動でUserモデルへの参照として取り扱ってくれるので、class_nameの記述は不要ですが、belongs_toの記述は必要です。

**Comment by kjmtks** [comment]
上記を記述することで、Thingモデルにownerメソッドが追加されます。
ownerメソッドは引数無し戻り値はUserです。
Rubyの場合引数無しのメソッドの呼び出しではカッコを省略できるので、
thinng.owner.email
でThnigにownerで関連づけられたUserのemailフィールドにアクセスできます

**Comment by kjmtks** [comment]
db/seeds.rbを以下のように変更します。

``` db/seeds.rb
user = User.find(1)
Thing.create({
  name: "なまえ",
  price: 100,
  amount: 2,
  category: "Category",
  owner: user,
})
```

まずDBをリセットします。
`rake db:migrate:reset`

その後でアプリを起動し、あたらしいユーザーを作成（Signup）します。

次にseedを入力します
`rake db:seed`

**Comment by kjmtks** [comment]
解決したようなのでClose
