### ISSUE TITLE
特定のOwnerのThingsをRecipt経由で取得する方法

### ISSUE THREAD

**Issue by kjmtks** [NIT-Anan-Procon/rails_pokereg#7]
関連が複雑になると、用意されているメソッドで対処できない。
結局SQLのJOINなんかを考えないといけない。
Railsは標準でArelというDBとのやりとりを抽象化するエンジンを使っていて、
これを使うことで複雑なやりとりも実現できるが、
ほとんどSQL書いてるのと代わらないかそれより複雑化するため少々周りくどい。

実は生のSQLを書く方法がある。
今回はArelを勉強している暇もないし、SQLの勉強のためにその方がいいかも。

具体的な方法は後で示すとして、とりあえずSQLでどうすればいいか考えてみようか。
まずはSQLITE3をインストールして、 db/developemnt.sqlite3に生SQLを送ってみよう

**Comment by haruka0000** [comment]
![screenshot from 2015-03-09 21 15 14](https://cloud.githubusercontent.com/assets/8327769/6554657/8cdfa28e-c6a1-11e4-928e-74726ad68fe8.png)
とりあえず練習でサンプルデータを入れてみました。

データを取り出す際はsqlのコードを埋め込んでデータを取得するということですか？
![screenshot from 2015-03-09 21 30 10](https://cloud.githubusercontent.com/assets/8327769/6554898/b556a152-c6a3-11e4-908c-f829c45be368.png)
今、入っているデータの取得はコマンドライン上では試してみました。
whereを使って必要なデータをしぼるんですよね。

**Comment by kjmtks** [comment]
そうですね。 whereをつかいます。テーブルの結合をしないといけないことに注意してくださいね

**Comment by haruka0000** [comment]
結合のことについて見てみたのですが、今回の場合、今のデータの持ち方を結合を意識したデータの持ち方に変更するほうがいいのでしょうか？
それとも、今のデータの持ち方そのままでもいけそうでしょうか？

**Comment by kjmtks** [comment]
データ構造は今のままでいいですよ。
確かにデータ構造変えるとよりシンプルになるかもしれませんが、この程度の結合は頻繁に出てくるので、勉強も兼ねてやってみましょう

**Comment by haruka0000** [comment]
references型のownerをｓｑｌで結合しようとしても「そのようなカラムはない」とエラーになります。
他のカラムで試すと大丈夫なのですが、references型のreceiptでも同じようになります。
references型の値を現在は結合条件にしようと考えていたのですが、references型は結合できないんでしょうか？
それとも、方法が間違えてるんですかね？

sqlite> select \* from users inner join receipts on users.id = receipts.owner;
Error: no such column: receipts.owner

でしました。

**Comment by kjmtks** [comment]
migrationでreferencesとしてものはサフィックス_idがつきます。
つまり、 Receiptモデルのowner参照の実態は、`receipts.owner_id`です。
なので、

```
select * from users inner join receipts on users.id = receipts.owner_id;
```

を試してみてください。

また、`select *`は取れる列全部取るのですが、いま欲しいのは`receipts`の情報なので、

```
select receipts.* from users inner join receipts on users.id = receipts.owner_id;
```

としてください。
あとはこれに`where`で条件を付ければOKです

**Comment by kjmtks** [comment]
Railsで生SQL使ってモデルを取得するには次のようにするそうです。

```
sql = "SQL文をここにかく"
# 取得したいモデルの find_by_sqlメソッドを呼び出す
Receipt.find_by_sql(sql)
```

**Comment by haruka0000** [comment]
テーブルを結合したとして、current_userのデータだけを表示するにはどうしたらいいのでしょうか？
３つのデータ(users, receipts, things)を結合してできたテーブルからwhereでcurrent_userを絞るのでしょうか？

あと、３つのデータの結合について調べましたが、よくわからないので教えてください。

**Comment by kjmtks** [comment]
いろいろ仕様が変わってきたので、改めてやりたいこと整理しましょうか。

まずcurrent_userがOwnerのReceiptを取得したいんですよね。なら以下でOK

```
receipts = Receipt.where(owner_id: current_user.id)
# もしくは Receipt.where(owner: current_user)
```

そして各Receiptに属するthingsに対して何らかの出力をしたい。例えば以下のようにかく。

```
<% receipts.each{|r| %>
  <% r.things.each{|t| %>
    <%= t.price %>
  <% } %>
<% } %>
```

**Comment by kjmtks** [comment]
DBアクセスの回数が多く効率的ではありませんが、今回はこれでもいいと思います。

**Comment by haruka0000** [comment]
では、結合はreceiptsとusersの２つだけでいいということでしょうか？

それとも、上記のものは３つを結合してからのことでしょうか？

**Comment by kjmtks** [comment]
今日、話した仕様の変更で、結合も必要ないし結局生SQL各必要がなくなったわけです。

**Comment by haruka0000** [comment]
やっぱりそうですよね。
では、現在上げてるものを少し直せばいけそうです。

**Comment by haruka0000** [comment]
![screenshot from 2015-03-11 22 48 30](https://cloud.githubusercontent.com/assets/8327769/6597543/ccafa576-c840-11e4-8de3-bf0ff78c5c4f.png)
いけたっぽいです。一応レシートカラムも表示させてみました。

<br>
<br>
<br>
<br>
![screenshot from 2015-03-11 22 48 45](https://cloud.githubusercontent.com/assets/8327769/6597565/f9d61b98-c840-11e4-9318-544601f8e00d.png)
他のユーザーでログインすると、ちゃんと表示されない仕様になってます。
pushしておきます。

**Comment by kjmtks** [comment]
おつかれさま！
